/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package tutorial;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-10-23")
public class resultDto implements org.apache.thrift.TBase<resultDto, resultDto._Fields>, java.io.Serializable, Cloneable, Comparable<resultDto> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("resultDto");

  private static final org.apache.thrift.protocol.TField C_FIELD_DESC = new org.apache.thrift.protocol.TField("c", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField SC_FIELD_DESC = new org.apache.thrift.protocol.TField("sc", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new resultDtoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new resultDtoTupleSchemeFactory());
  }

  public int c; // required
  public String sc; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    C((short)1, "c"),
    SC((short)2, "sc");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // C
          return C;
        case 2: // SC
          return SC;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __C_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.C, new org.apache.thrift.meta_data.FieldMetaData("c", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SC, new org.apache.thrift.meta_data.FieldMetaData("sc", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(resultDto.class, metaDataMap);
  }

  public resultDto() {
  }

  public resultDto(
    int c,
    String sc)
  {
    this();
    this.c = c;
    setCIsSet(true);
    this.sc = sc;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public resultDto(resultDto other) {
    __isset_bitfield = other.__isset_bitfield;
    this.c = other.c;
    if (other.isSetSc()) {
      this.sc = other.sc;
    }
  }

  public resultDto deepCopy() {
    return new resultDto(this);
  }

  @Override
  public void clear() {
    setCIsSet(false);
    this.c = 0;
    this.sc = null;
  }

  public int getC() {
    return this.c;
  }

  public resultDto setC(int c) {
    this.c = c;
    setCIsSet(true);
    return this;
  }

  public void unsetC() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __C_ISSET_ID);
  }

  /** Returns true if field c is set (has been assigned a value) and false otherwise */
  public boolean isSetC() {
    return EncodingUtils.testBit(__isset_bitfield, __C_ISSET_ID);
  }

  public void setCIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __C_ISSET_ID, value);
  }

  public String getSc() {
    return this.sc;
  }

  public resultDto setSc(String sc) {
    this.sc = sc;
    return this;
  }

  public void unsetSc() {
    this.sc = null;
  }

  /** Returns true if field sc is set (has been assigned a value) and false otherwise */
  public boolean isSetSc() {
    return this.sc != null;
  }

  public void setScIsSet(boolean value) {
    if (!value) {
      this.sc = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case C:
      if (value == null) {
        unsetC();
      } else {
        setC((Integer)value);
      }
      break;

    case SC:
      if (value == null) {
        unsetSc();
      } else {
        setSc((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case C:
      return getC();

    case SC:
      return getSc();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case C:
      return isSetC();
    case SC:
      return isSetSc();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof resultDto)
      return this.equals((resultDto)that);
    return false;
  }

  public boolean equals(resultDto that) {
    if (that == null)
      return false;

    boolean this_present_c = true;
    boolean that_present_c = true;
    if (this_present_c || that_present_c) {
      if (!(this_present_c && that_present_c))
        return false;
      if (this.c != that.c)
        return false;
    }

    boolean this_present_sc = true && this.isSetSc();
    boolean that_present_sc = true && that.isSetSc();
    if (this_present_sc || that_present_sc) {
      if (!(this_present_sc && that_present_sc))
        return false;
      if (!this.sc.equals(that.sc))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_c = true;
    list.add(present_c);
    if (present_c)
      list.add(c);

    boolean present_sc = true && (isSetSc());
    list.add(present_sc);
    if (present_sc)
      list.add(sc);

    return list.hashCode();
  }

  @Override
  public int compareTo(resultDto other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetC()).compareTo(other.isSetC());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetC()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.c, other.c);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSc()).compareTo(other.isSetSc());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSc()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sc, other.sc);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("resultDto(");
    boolean first = true;

    sb.append("c:");
    sb.append(this.c);
    first = false;
    if (!first) sb.append(", ");
    sb.append("sc:");
    if (this.sc == null) {
      sb.append("null");
    } else {
      sb.append(this.sc);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class resultDtoStandardSchemeFactory implements SchemeFactory {
    public resultDtoStandardScheme getScheme() {
      return new resultDtoStandardScheme();
    }
  }

  private static class resultDtoStandardScheme extends StandardScheme<resultDto> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, resultDto struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // C
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.c = iprot.readI32();
              struct.setCIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SC
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.sc = iprot.readString();
              struct.setScIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, resultDto struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(C_FIELD_DESC);
      oprot.writeI32(struct.c);
      oprot.writeFieldEnd();
      if (struct.sc != null) {
        oprot.writeFieldBegin(SC_FIELD_DESC);
        oprot.writeString(struct.sc);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class resultDtoTupleSchemeFactory implements SchemeFactory {
    public resultDtoTupleScheme getScheme() {
      return new resultDtoTupleScheme();
    }
  }

  private static class resultDtoTupleScheme extends TupleScheme<resultDto> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, resultDto struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetC()) {
        optionals.set(0);
      }
      if (struct.isSetSc()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetC()) {
        oprot.writeI32(struct.c);
      }
      if (struct.isSetSc()) {
        oprot.writeString(struct.sc);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, resultDto struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.c = iprot.readI32();
        struct.setCIsSet(true);
      }
      if (incoming.get(1)) {
        struct.sc = iprot.readString();
        struct.setScIsSet(true);
      }
    }
  }

}

